import psycopg2
import traceback
from sshtunnel import SSHTunnelForwarder
try:
   with SSHTunnelForwarder(
         ('54.200.37.1', 22),
         #ssh_private_key="</path/to/private/ssh/key>",
         ### in my case, I used a password instead of a private key
         ssh_username="USERNAMEFORSERVER",
         ssh_private_key= r"SSHKEYLOCATION",
         remote_bind_address=('PUTHOSTHERE', 5432)) as server:
         
         server.start()
         print ("server connected")
         params = {
             'database': 'DBNAME',
             'user': 'USERNAME',
             'password': 'PASSWORD',
             'host': 'localhost',
             'port': server.local_bind_port
             }
         conn = psycopg2.connect(**params)
         curs = conn.cursor()
         print ("database connected")
except:
    print ("Connection Failed")
